services:
  - type: web
    name: kindsteps-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "python -m app.initial_setup && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
